[package]
org = "tumashadeshan"
name = "competition_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
path = "./lib/postgresql-42.7.4.jar"
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.4"
